# dependencies for structural color package
#
# To use:
#   conda env create -f environment.yml
# and then
#   conda activate structcol
#
# To update dependencies after changing this environment file:
#   conda env update --name structcol --file environment.yml --prune
#
# can also use mamba instead of conda in the above
name: structcol
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - pandas
  - pint
  - ipython
  - matplotlib
  - seaborn

  # include jupyterlab for convenience
  - jupyterlab

  # for running tests
  - pytest

  # for linting
  - ruff

  # for installing other dependencies
  - pip
